version: '3.1'

services:

  db:
    image: mysql
    command: > 
      --default-authentication-plugin=mysql_native_password
      && --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./docker/volumes/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080