name: Workflow
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
    branches:    
      - '*'
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun lint
  
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun test
    needs: lint
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      # Core need to be build before other packages because some need there types
      - run: bun run build --filter=@cosmoosjs/core
      - run: bun run build
    needs: tests